-- =========================================================================
-- Exercise 5: Triggers
-- =========================================================================

-- Note: For Scenario 2, we need an AuditLog table. Let's create it first.
CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TableName VARCHAR2(50),
    Operation VARCHAR2(20),
    RecordID NUMBER,
    AuditDate DATE
);

-- -------------------------------------------------------------------------
-- Scenario 1: UpdateCustomerLastModified Trigger
-- Description: Automatically update LastModified date on update.
-- -------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- -------------------------------------------------------------------------
-- Scenario 2: LogTransaction Trigger
-- Description: Maintain an audit log for all transactions.
-- -------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TableName, Operation, RecordID, AuditDate)
    VALUES ('Transactions', 'INSERT', :NEW.TransactionID, SYSDATE);
END;
/

-- -------------------------------------------------------------------------
-- Scenario 3: CheckTransactionRules Trigger
-- Description: Enforce business rules on deposits and withdrawals.
-- -------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_CurrentBalance NUMBER;
BEGIN
    -- Check deposit rules
    IF :NEW.TransactionType = 'Deposit' AND :NEW.Amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Deposit amount must be strictly positive.');
    END IF;

    -- Check withdrawal rules
    IF :NEW.TransactionType = 'Withdrawal' THEN
        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Withdrawal amount must be strictly positive.');
        END IF;

        -- Check sufficient balance for withdrawal
        SELECT Balance INTO v_CurrentBalance FROM Accounts WHERE AccountID = :NEW.AccountID;
        
        IF :NEW.Amount > v_CurrentBalance THEN
            RAISE_APPLICATION_ERROR(-20003, 'Withdrawal exceeds current balance.');
        END IF;
    END IF;
END;
/
